version: '3.8'

services:
  db:
    image: postgres:16
    container_name: testify_local_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: testify
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data